### ISSUE TITLE
Remove tests from packages (composer)

### ISSUE THREAD

**Issue by ibrahimBeladi** [usernane/webfiori#8]
Exclude tests from the package when install from composer. And move the dependency management to be from composer and not via downloading.

**Comment by usernane** [comment]
Have been reading about this issue for the last few days. It seems there is no standard way to do it. Some authors of composer suggest the use of .gitattributes but in my opinion it is not the best solution. 
I have been reading through https://ithub.com/composer/composer/issues/1750 and https://github.com/composer/composer/issues/4438. According to what I have seen, they say that it is the job of the developer to clean up what he needs and what is not needed.

What do you think @ibrahimBeladi ?

**Comment by ibrahimBeladi** [comment]
** composer/composer#1750

**Comment by ibrahimBeladi** [comment]
In my opinion, the output (the package) should not contain any tests and the tests should be done by the maintainer(s). If it is possible to selectively get the tests that would be a bonus. But ideally, I would prefer not to have someone's tests on my machine. I am not sure if there are solutions for this, because is is too old now. But, it would not hurt to try.

**Comment by peter279k** [comment]
I think it can also consider using the `.gitattributes` to accomplish this issue.

Some related PRs are as follows:

- https://github.com/elastic/elasticsearch-php/pull/844
- https://github.com/twigphp/Twig/pull/3153
- https://github.com/symfony/symfony/pull/33579

**Comment by usernane** [comment]
For the time being, this will be applied to the framework it self but not the libraries at which it depends on. The thing is that currently, the libraries that the framework depends on are in the folder `entity`.  If composer is used, then every thing will be moved to `vendor` which is outside the scope of the framework. 

The framework has its own mechanism to auto load classes. The implementation can be found in the class [AutoLoader](https://github.com/usernane/webfiori/blob/master/src/entity/AutoLoader.php) The auto-loader of the framework will force you to use object oriented approach. One of the things that I don't like about composer is that it has some code which is not fully object oriented in the auto-loader implementation. 

Will consider the ability to load dependent libraries for the future using composer.

**Comment by peter279k** [comment]
@usernane, thanks for your reply.

IMHO, I think we can provide two approaches about that you mention.

We can use the composer to load classes automatically or using customized autoloader without composer to load classes.

And it can be convenient for Composer fan to use/enjoy this framework :).
